name: portfolio
description: "My portfolio ! This project is about my portfolio."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  animated_text_kit: ^4.2.3
  carousel_slider: ^5.0.0
  connectivity_plus: ^6.1.3
  cupertino_icons: ^1.0.8
  curved_navigation_bar: ^1.0.6
  dio: ^5.7.0
  equatable: ^2.0.7
  firebase_data_connect: ^0.1.3+2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_localization: ^0.3.1
  flutter_secure_storage: ^9.2.4
  go_router: ^14.6.3
  google_fonts: ^6.2.1
  http: ^1.2.2
  image_picker: ^1.1.2
  intl: ^0.19.0
  lottie: ^3.3.0
  scrollable_positioned_list: ^0.3.8
  shared_preferences: ^2.5.2
  sizer: ^3.0.5
  universal_html: ^2.2.4
  url_launcher: ^6.3.1
  url_strategy: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/imgs/
    - assets/imgs/icons/
    - assets/imgs/logos/
    - assets/imgs/photos/
    - assets/imgs/photos/projects/
    - assets/animations/
